import {
  type Icon as LucideIcon,
  Orbit,
  LayoutDashboard,
  Route,
  MapPin,
  Truck,
  UsersRound,
  Loader2,
  LogOut,
  PlusCircle,
  MoreHorizontal,
  FileText,
  AlertCircle,
  Database,
  Pencil,
  FileBarChart,
  CalendarDays,
  ClipboardList,
  Shield,
  BookUser,
  Settings,
  Trash2,
  ArrowUpRight,
  ArrowDownLeft,
  Wallet,
} from 'lucide-react'

export type Icon = typeof LucideIcon

export const Icons = {
  logo: Orbit,
  dashboard: LayoutDashboard,
  route: Route,
  address: MapPin,
  fleet: Truck,
  customers: UsersRound,
  spinner: Loader2,
  logout: LogOut,
  add: PlusCircle,
  more: MoreHorizontal,
  invoice: FileText,
  issue: AlertCircle,
  database: Database,
  edit: Pencil,
  reports: FileBarChart,
  calendar: CalendarDays,
  orders: ClipboardList,
  admin: Shield,
  accounting: BookUser,
  settings: Settings,
  delete: Trash2,
  income: ArrowUpRight,
  expense: ArrowDownLeft,
  wallet: Wallet,
}

    